import 'package:flutter/material.dart';

class Product {
  String? image, title, description, sellerName, companyName, type, deliveryType, dealingMethod, category, productID, from, to, expDate, userID,
      unit, oid, sellerEmail, condition, subcategory, status;
  int? qty, id, inStock, period;
  final double price, unitPrice;
  bool ? isDraft, isNonNegotiable;
  Product({
    this.id,
    this.image,
    this.title,
    required this.price,
    this.description,
    this.qty,
    this.sellerName,
    this.companyName,
    required this.unitPrice,
    this.category,
    this.type,
    this.deliveryType,
    this.dealingMethod,
    this.inStock,
    this.productID,
    this.from,
    this.to,
    this.expDate,
    this.userID,
    this.period,
    this.unit,
    this.oid,
    this.sellerEmail,
    this.subcategory,
    this.condition,
    this.isDraft,
    this.status,
    this.isNonNegotiable

  });
}

List<Product> products = [
  Product(
    id: 1,
    title: "Bulldozer",
    price: 234,
    qty: 12,
    description: dummyText,
    image: "assets/images/sampleItems/bulldozer.png",
    sellerName: "Chan Bandara",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
    from: "12/10/2023",
    to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true
  ),
  Product(
    id: 2,
    title: "Floor Polisher",
    price: 234,
    qty: 8,
    description: dummyText,
    image: "assets/images/sampleItems/floorPolisher.png",
    sellerName: "Sachini Madushika",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
      from: "12/10/2023",
      to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true

  ),
  Product(
    id: 3,
    title: "Generator",
    price: 234,
    qty: 10,
    description: dummyText,
    image: "assets/images/sampleItems/geni.png",
    sellerName: "Abhishek Fernando",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
      from: "12/10/2023",
      to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true

  ),
  Product(
    id: 4,
    title: "Construction Helmet",
    price: 234,
    qty: 11,
    description: dummyText,
    image: "assets/images/sampleItems/helmet.png",
    sellerName: "Viroj Fernandp",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
      from: "12/10/2023",
      to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true

  ),
  Product(
    id: 5,
    title: "Bulldozer",
    price: 234,
    qty: 12,
    description: dummyText,
    image: "assets/images/sampleItems/bulldozer.png",
    sellerName: "Heshan Fernando",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
      from: "12/10/2023",
      to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true

  ),
  Product(
    id: 6,
    title: "Construction Helmat",
    price: 234,
    qty: 12,
    description: dummyText,
    image: "assets/images/sampleItems/helmet.png",
    sellerName: "Minuki Liyora",
    companyName: "ABC Media",
    unitPrice: 4.00,
    category: "Tools",
    type: "Sale",
    deliveryType: "on site delivery",
    dealingMethod: "direct deal",
    inStock: 4,
    productID: "#639a913ea1a6a096cc963333",
      from: "12/10/2023",
      to: "30/11/2023",
      expDate: "07/12/2023",
      userID: "001",
      period:3,
      unit:"",
      oid:"",
      sellerEmail:"abc@gmail.com",
      subcategory: "",
      condition: "",
      isDraft: true,
      status: "",
      isNonNegotiable: true
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
